version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: daily
      time: "15:30"
    labels:
      - "composer"
      - "dependencies"
    assignees:
      - "rubenwebparking"
      - "lreijmer"
